version: 3.7

services:
    gin:
        build:
        #If the image does not exist, Compose attempts to pull it, unless you have also specified build,
        #in which case it builds it using the specified options and tags it with the specified tag.
        #https://docs.docker.com/compose/compose-file/compose-file-v3/
            context: ./gin
            dockerfile: Dockerfile

        image: public.ecr.aws/w5v4j9k4/tsagroup_rupertbailey:latest
        container_name: gin
        restart: always
        ports:
            - "3004:3004"

    postgres:
        image: docker.io/library/postgres:latest
        container_name: postgres
        environment:
          POSTGRES_PASSWORD: mypass
          POSTGRES_HOST_AUTH_METHOD: trust
          #APP_DB_USER: tsauser
          #APP_DB_PASS: tsapass
          #APP_DB_NAME: tsagroup
        volumes:
          - ./pg_init:/docker-entrypoint-initdb.d:Z
          #- ./pg_data:/var/lib/postgresql/data:Z
        ports:
          - '5432:5432'
